#!/bin/bash

# If you modify the behaviour of this file please remember to update the
# relevant wiki page:
#
# https://github.com/links-lang/links/wiki/Running-the-test-suite

ret=0

if [[ $1 != "db-only" ]]; then
    for i in tests/*.tests; do
        cmnd="./test-harness $i"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [ $ret_code != 0 ]; then
            ret=1
        fi
    done
fi

DB_TEST_DIR=tests/database

if [[ $1 != "no-db" ]]; then
    for s in $DB_TEST_DIR/*.sql; do
        cmnd="psql -v ON_ERROR_STOP=1 -q -d links -f $s"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [ $ret_code != 0 ]; then
            echo "FAILED DATABASE PREPARATION $s"
            ret=1
        fi
    done

    while read t; do
        expect_broken=0
        line=($t)
        if (( ${#line[@]} > 1 )); then
          t=${line[1]}
          expect_broken=1
        fi
        cmnd="./links --config=$DB_TEST_DIR/config $DB_TEST_DIR/$t.links"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [[ ($ret_code -ne 0 && expect_broken -eq 0) || ($ret_code -eq 0 && expect_broken -ne 0) ]]; then
            echo "FAILED TEST $t"
            ret=1
        fi
    done < "$DB_TEST_DIR/testsuite.config"
fi

exit $ret
